apiVersion: v1
kind: ConfigMap
metadata:
  name: sorter-config
  namespace: flame-ai
  labels:
    app.kubernetes.io/name: sorter
    app.kubernetes.io/part-of: flame-ai
data:
  PYROSCOPE_SERVER_ADDRESS: "http://pyroscope.observability.svc.cluster.local:4040"
  PYROSCOPE_APPLICATION_NAME: "flame-ai.sorter"
  PYROSCOPE_ENV: "minikube"
  SORTER_DEFAULT_N: "5000"
